version: "3.4"

services:
  api:
    container_name: annotation_api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - .env:/app/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3654:8000"
    networks:
      - annotation_nw

  db:
    container_name: annotation_db
    image: postgres:14-alpine
    healthcheck:      
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h 127.0.0.1"]     
      interval: 10s      
      timeout: 5s      
      retries: 3      
      start_period: 60s
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}      
      POSTGRES_USER: ${DB_USER}
    networks:
      - annotation_nw

  minio:
    container_name: annotation_minio
    image: minio/minio
    volumes:
      - minio_data:/data
    healthcheck:      
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]      
      interval: 30s      
      timeout: 20s      
      retries: 3
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}      
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address :9001 /data
    networks:
      - annotation_nw


volumes:
  db_data:
  minio_data:

networks:
  annotation_nw:
    external: false